---
title: "Final Project Assignment 1"
author: "Bradley Monarch"
date: "3/13/2023"
output:
  rmdformats::material:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE, eval = TRUE,
                      message = FALSE, warning = FALSE)
```

```{r}
library(data.table)
library(tidyverse)
library(knitr)
library(arrow)
library(bench)
library(ggbeeswarm)
library(haven)
library(stringr)
library(lubridate)
library(ggpubr)
library(skimr)
```


### Import Data

```{r}
gunData <- data.table::fread("gunViolenceFull.csv")
```

### Explore and display high-level characteristics of your data set, e.g., important variables and their types, different levels for factor variables, any patterns of missing values.

```{r}
summary(gunData)
glimpse(gunData)
skim(gunData)
```

Obtain at least two tables of group-level summary statistics for quantitative variables in your data set.


```{r}
#Summary statistics for number of people killed
gunData %>% pull(n_killed) %>% summary()

```

```{r}
#Summary statistics for number of people injured
gunData %>% pull(n_injured) %>% summary()

```







